# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b543afdd0a40e69006f120797c9b20eeadcedde1abd8423de2582ce95c8356a5fb0eacbd7b4969d2089f311b7b7a31cc097caa5b0295ebe512c42a037886faf6

test:
  secret_key_base: bee05045a062bbfd05781ceefc15fa0841e0bae0c1b24ff09f1e6815863558c5d2ab29e7576d7d56bac5430e8aa2930c87c1596ad130ef1468fd6da0ad6bee42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
